// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxfjNR1266IDQu5byZXikp779RjrHd3TM',
    appId: '1:79796111678:android:53d4606bdc171286dbc46f',
    messagingSenderId: '79796111678',
    projectId: 'magma-chat-96c22',
    storageBucket: 'magma-chat-96c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq9zcTorXZ4j95lXp71GsvojzuFigcAcQ',
    appId: '1:79796111678:ios:bf18d81722e9ab9edbc46f',
    messagingSenderId: '79796111678',
    projectId: 'magma-chat-96c22',
    storageBucket: 'magma-chat-96c22.appspot.com',
    androidClientId: '79796111678-ue15tkcm2ko64fb7de0egi0c5rmv12rm.apps.googleusercontent.com',
    iosClientId: '79796111678-guu1jkumur40t8n9vojakmj88odm7s61.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}